fix broken jenkins build

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -1,6 +1,5 @@
 #!/bin/bash -e
 
-export PATH=$OPENSHIFT_LIBERTY_DIR/ruby193:$PATH
 source $OPENSHIFT_CARTRIDGE_SDK_BASH
 
 liberty_dir=$OPENSHIFT_LIBERTY_DROPLET_DIR/.liberty
@@ -14,11 +13,9 @@ restage_marker=$OPENSHIFT_LIBERTY_DIR/.app
 
 
 function isrunning() {
-  if [ -f "$server_pid_file" ]
-  then
+  if [ -f "$server_pid_file" ]; then
     pid=$(cat $server_pid_file);
-    if ps -p $pid 1>&2 > /dev/null
-    then
+    if ps -p $pid 1>&2 > /dev/null; then
       return 0
     fi
   fi
@@ -29,8 +26,7 @@ function ishttpup() {
   count=0
   while [ ${count} -lt 64 ]
   do
-    if lsof -P -n -i "@${OPENSHIFT_LIBERTY_IP}:${OPENSHIFT_LIBERTY_HTTP_PORT}" | grep "(LISTEN)" > /dev/null
-    then
+    if lsof -P -n -i "@${OPENSHIFT_LIBERTY_IP}:${OPENSHIFT_LIBERTY_HTTP_PORT}" | grep "(LISTEN)" > /dev/null; then
       echo "Found ${OPENSHIFT_LIBERTY_IP}:${OPENSHIFT_LIBERTY_HTTP_PORT} listening port"
       return 0
     fi
@@ -66,15 +62,13 @@ killtree() {
     fi
   done
   local should_be_gone_pid=$(ps -o pid -p ${_pid} --no-headers)
-  if [ ! -z $should_be_gone_pid ]
-  then
+  if [ ! -z "$should_be_gone_pid" ]; then
     kill -9 ${_pid}
   fi
 }
 
 function status() {
-  if isrunning
-  then
+  if isrunning; then
     client_result "app is running"
   else
     client_result "app is stopped"
@@ -82,12 +76,10 @@ function status() {
 }
 
 function extract_archives() {
-  echo "searching $1"
   for f in $1/*
   do
-    if [[ $f =~ \.war$ ]] || [[ $f =~ \.ear$ ]]
-    then
-      echo "extracting $f"
+    if [[ $f =~ \.war$ ]] || [[ $f =~ \.ear$ ]]; then
+      echo "found $f"
       pushd $OPENSHIFT_LIBERTY_DROPLET_DIR 1> /dev/null
         jar xf $f
       popd 1> /dev/null
@@ -99,19 +91,16 @@ function deploy() {
   rm -rf $OPENSHIFT_LIBERTY_DROPLET_DIR/*
   rm -rf $OPENSHIFT_LIBERTY_DROPLET_DIR/.[a-z]*
   touch $restage_marker
-  if [ -f "$OPENSHIFT_REPO_DIR/pom.xml" ]
-  then
+  if [ -f "$OPENSHIFT_REPO_DIR/pom.xml" ]; then
     echo "found possible build from source"
     extract_archives $OPENSHIFT_REPO_DIR/apps 
-  elif ls $OPENSHIFT_REPO_DIR/*.zip 1>&2 > /dev/null
-  then
+  elif ls $OPENSHIFT_REPO_DIR/*.zip 1>&2 > /dev/null; then
     echo "found possible server package"
     unzip -q $(ls $OPENSHIFT_REPO_DIR/*.zip) -d $OPENSHIFT_LIBERTY_DROPLET_DIR
     mv $OPENSHIFT_LIBERTY_DROPLET_DIR/wlp/usr/servers/* $OPENSHIFT_LIBERTY_DROPLET_DIR/wlp/usr/servers/$server_name
     rm -rf $server_dir/logs
     rm -rf $server_dir/workarea
-  elif [ -f "$OPENSHIFT_REPO_DIR/server.xml" ]
-  then
+  elif [ -f "$OPENSHIFT_REPO_DIR/server.xml" ]; then
     echo "found possible server directory"
     rsync -r --exclude ".*" $OPENSHIFT_REPO_DIR/ $OPENSHIFT_LIBERTY_DROPLET_DIR/
   else
@@ -126,8 +115,7 @@ function tidy() {
 }
 
 function threaddump() {
-  if ! isrunning
-  then
+  if ! isrunning; then
     echo "app is stopped"
     exit 1
   else
@@ -145,22 +133,19 @@ function create_credentials() {
 function create_vcap_services() {
   var="{"
   # postgresql 9.2
-  if [ -n "$OPENSHIFT_POSTGRESQL_DB_HOST" ]
-  then
+  if [ -n "$OPENSHIFT_POSTGRESQL_DB_HOST" ]; then
     label="postgresql"
     creds=$(create_credentials $OPENSHIFT_POSTGRESQL_DB_USERNAME $OPENSHIFT_POSTGRESQL_DB_PASSWORD $OPENSHIFT_POSTGRESQL_DB_HOST $OPENSHIFT_POSTGRESQL_DB_PORT $OPENSHIFT_APP_NAME $OPENSHIFT_POSTGRESQL_DB_URL)
     var+="\"$label\":[{\"name\":\"my$label\",\"label\":\"$label\",\"tags\":[\"$label\"],$creds}],"
   fi
   # mysql 5.1 or mariadb 5.5
-  if [ -n "$OPENSHIFT_MYSQL_DB_HOST" ]
-  then
+  if [ -n "$OPENSHIFT_MYSQL_DB_HOST" ]; then
     label="mysql"
     creds=$(create_credentials $OPENSHIFT_MYSQL_DB_USERNAME $OPENSHIFT_MYSQL_DB_PASSWORD $OPENSHIFT_MYSQL_DB_HOST $OPENSHIFT_MYSQL_DB_PORT $OPENSHIFT_APP_NAME $OPENSHIFT_MYSQL_DB_URL)
     var+="\"$label\":[{\"name\":\"my$label\",\"label\":\"$label\",\"tags\":[\"$label\"],$creds}],"
   fi
   # mongodb 2.2
-  if [ -n "$OPENSHIFT_MONGODB_DB_HOST" ]
-  then
+  if [ -n "$OPENSHIFT_MONGODB_DB_HOST" ]; then
     label="mongodb"
     creds=$(create_credentials $OPENSHIFT_MONGODB_DB_USERNAME $OPENSHIFT_MONGODB_DB_PASSWORD $OPENSHIFT_MONGODB_DB_HOST $OPENSHIFT_MONGODB_DB_PORT $OPENSHIFT_APP_NAME $OPENSHIFT_MONGODB_DB_URL)
     var+="\"$label\":[{\"name\":\"my$label\",\"label\":\"$label\",\"tags\":[\"$label\"],$creds}],"
@@ -179,8 +164,7 @@ function stage() {
   services_hash=($(echo $VCAP_SERVICES | md5sum))
   old_services_hash=$(cat $services_hash_file) 
   echo $services_hash > $services_hash_file
-  if [ -f $restage_marker ] || [ "$services_hash" != "$old_services_hash" ]
-  then 
+  if [ -f "$restage_marker" ] || [ "$services_hash" != "$old_services_hash" ]; then
     echo "generated VCAP_APPLICATION=$VCAP_APPLICATION"
     echo "generated VCAP_SERVICES=$VCAP_SERVICES"
     # verify valid app
@@ -210,8 +194,7 @@ function stage() {
 function join_jvm_args() {
   local IFS="$1"
   shift
-  if [ "$*" == "" ]
-  then
+  if [ "$*" == "" ]; then
     echo ""
   else
     echo "\"\"$*\"\""
@@ -219,17 +202,18 @@ function join_jvm_args() {
 }
 
 function start() {
-  if isrunning
-  then
+  if [ -z "$IBM_LIBERTY_LICENSE" ]; then
+    echo "missing Liberty license, set IBM_LIBERTY_LICENSE env var"
+    exit 0 # in a Jenkins build this won't be set but it's okay to not stage and start
+  fi
+  if isrunning; then
     echo "app is already running"
   else
     stage
-    if marker_present "clean_start"
-    then
+    if marker_present "clean_start"; then
       server_opts="--clean"
     fi
-    if marker_present "enable_jpda"
-    then
+    if marker_present "enable_jpda"; then
       debug_args=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=$OPENSHIFT_LIBERTY_JPDA_PORT
     fi
     # in CF the DEA would run a similar start command based on bin/release output
@@ -241,8 +225,7 @@ function start() {
     echo $! > $server_pid_file
     rc=0
     ishttpup || rc=$?
-    if [ $rc -eq 1 ]
-    then
+    if [ $rc -eq 1 ]; then
       echo "Timed out waiting for http listening port for Liberty"
       exit 1
     fi
@@ -250,8 +233,7 @@ function start() {
 }
 
 function stop() {
-  if isrunning
-  then
+  if isrunning; then
     pid=$(cat $server_pid_file);
     killtree $pid
   else
